import { BuildingDef } from '../world/def-database';

export const BUILDING_DEFS: BuildingDef[] = [
  {
    defId: 'wall_wood',
    label: 'Wood Wall',
    description: 'A simple wooden wall.',
    size: { width: 1, height: 1 },
    maxHp: 150,
    workToBuild: 100,
    costList: [{ defId: 'wood', count: 5 }],
    tags: ['structure', 'wall', 'impassable'],
    blocksMovement: true,
    blocksLight: true,
    passable: false,
    color: 0x8B6914,
  },
  {
    defId: 'wall_stone',
    label: 'Stone Wall',
    description: 'A sturdy stone wall.',
    size: { width: 1, height: 1 },
    maxHp: 300,
    workToBuild: 200,
    costList: [{ defId: 'stone_block', count: 5 }],
    tags: ['structure', 'wall', 'impassable'],
    blocksMovement: true,
    blocksLight: true,
    passable: false,
    color: 0x777777,
  },
  {
    defId: 'door_wood',
    label: 'Wood Door',
    description: 'A wooden door. Colonists can open and close it.',
    size: { width: 1, height: 1 },
    maxHp: 100,
    workToBuild: 80,
    costList: [{ defId: 'wood', count: 3 }],
    tags: ['structure', 'door'],
    blocksMovement: false,
    blocksLight: true,
    passable: true,
    color: 0x6B4226,
  },
  {
    defId: 'bed_wood',
    label: 'Wood Bed',
    description: 'A simple bed for sleeping.',
    size: { width: 1, height: 2 },
    maxHp: 100,
    workToBuild: 120,
    costList: [{ defId: 'wood', count: 8 }],
    tags: ['furniture', 'bed'],
    blocksMovement: false,
    blocksLight: false,
    passable: false,
    interactionCellOffset: { x: 0, y: 2 },
    color: 0xCD853F,
  },
  {
    defId: 'table',
    label: 'Table',
    description: 'A table for eating.',
    size: { width: 2, height: 1 },
    maxHp: 100,
    workToBuild: 80,
    costList: [{ defId: 'wood', count: 6 }],
    tags: ['furniture', 'table'],
    blocksMovement: false,
    blocksLight: false,
    passable: false,
    color: 0xA0522D,
  },
  {
    defId: 'stockpile_zone_marker',
    label: 'Stockpile',
    description: 'A zone for storing items.',
    size: { width: 1, height: 1 },
    maxHp: 999,
    workToBuild: 0,
    costList: [],
    tags: ['zone_marker'],
    blocksMovement: false,
    blocksLight: false,
    passable: true,
    color: 0xFFFF00,
  },
];
