import { TerrainDef } from '../world/def-database';

export const TERRAIN_DEFS: TerrainDef[] = [
  {
    defId: 'grass',
    label: 'Grass',
    passable: true,
    moveCost: 1,
    fertility: 1,
    color: 0x4a7c3f,
    mineable: false,
  },
  {
    defId: 'dirt',
    label: 'Dirt',
    passable: true,
    moveCost: 1,
    fertility: 0.7,
    color: 0x8b7355,
    mineable: false,
  },
  {
    defId: 'sand',
    label: 'Sand',
    passable: true,
    moveCost: 1.5,
    fertility: 0.1,
    color: 0xc2b280,
    mineable: false,
  },
  {
    defId: 'rock',
    label: 'Rock',
    passable: false,
    moveCost: 999,
    fertility: 0,
    color: 0x666666,
    mineable: true,
    mineYield: { defId: 'stone_chunk', count: 2 },
  },
  {
    defId: 'water',
    label: 'Water',
    passable: false,
    moveCost: 999,
    fertility: 0,
    color: 0x3366aa,
    mineable: false,
  },
  {
    defId: 'floor_wood',
    label: 'Wood Floor',
    passable: true,
    moveCost: 0.8,
    fertility: 0,
    color: 0xa0825a,
    mineable: false,
  },
  {
    defId: 'floor_stone',
    label: 'Stone Floor',
    passable: true,
    moveCost: 0.8,
    fertility: 0,
    color: 0x999999,
    mineable: false,
  },
];
